# Generated by Django 6.0.5 on 2026-06-05 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='membership',
            table='membership',
        ),
    ]
