# Generated by Django 6.0.5 on 2026-06-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
