# Generated by Django 6.0.5 on 2026-06-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_subscription_duration_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='max_books',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='subscription',
            name='max_borrow_days',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
