# Generated by Django 6.0.5 on 2026-06-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('approval', 'Approval'), ('reservation', 'Reservation'), ('due_reminder', 'Due Reminder'), ('overdue', 'Overdue'), ('new_book', 'New Book Added'), ('announcement', 'Announcement'), ('fine', 'Fine Applied'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed')], max_length=30),
        ),
    ]
