# Generated by Django 6.0.5 on 2026-06-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_member_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='member/profile/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='qr_code',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='member',
            table='member',
        ),
    ]
