# Generated by Django 6.0.5 on 2026-06-06 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_member_is_active_alter_member_profile_image_and_more'),
        ('subscription', '0003_subscription_max_books_subscription_max_borrow_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='subscription.subscription'),
        ),
        migrations.AddField(
            model_name='member',
            name='subscription_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='subscription_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
