# Generated by Django 6.0.5 on 2026-06-03 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='author',
        ),
    ]
