# Generated by Django 6.0.5 on 2026-06-05 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0002_alter_book_cover_image'),
        ('member', '0003_alter_member_is_active_alter_member_profile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=20)),
                ('notified', models.BooleanField(default=False)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='book.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='member.member')),
            ],
            options={
                'db_table': 'reservation',
                'ordering': ['reserved_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'WAITING')), fields=('member', 'book'), name='unique_active_reservation')],
            },
        ),
    ]
