# Generated by Django 6.0.5 on 2026-06-05 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reservation',
            name='unique_active_reservation',
        ),
    ]
